version: '2.1'
services:
  db:
    image: postgres
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cretaker
    ports:
        - 5432:5432/tcp
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local

